modLoader="javafml"
loaderVersion="[47,)"
license="Assets: All Rights Reserved; Code: LGPL-3.0"
issueTrackerURL="https://github.com/The-Aether-Team/Overworld-Ores/issues"

[[mods]]
modId="aether_overworld_ores"
version="${file.jarVersion}"
displayName="Overworld Ores"
updateJSONURL="https://github.com/The-Aether-Team/Overworld-Ores/raw/1.20.1-develop/update.json"
displayURL="https://modrinth.com/mod/overworld-ores"
logoFile="overworld_ores_icon.png"
credits="The Aether Team"
authors="bconlon, Builderdog, Oz Payn"
description='''
TBA...
'''

[[dependencies.aether_overworld_ores]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aether_overworld_ores]]
    modId = "aether"
    mandatory = true
    versionRange = "[1.20.1-1.0.0-neoforge,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether_overworld_ores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"